#!/usr/bin/env python3
"""Generate deterministic ARIN v1 contract artifacts from canonical Pydantic models.

This generator emits OpenAPI-compatible component schemas and a small TypeScript
client type surface. It does not add routes, credentials, tool authority, or
physical-actuation capability.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import get_args

from src.control_plane.contracts.contracts import (
    ApprovalDecision,
    ApprovalResponse,
    ApprovalSubmitRequest,
    Goal,
    GoalVerb,
    IntentCreateRequest,
    Mode,
    PlanCreateRequest,
    PlanStep,
    RiskTier,
    SessionCreateRequest,
    SessionRenewRequest,
    SessionResponse,
    SessionStatus,
    SourceKind,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "arin" / "contracts"
MODELS = (
    Goal,
    IntentCreateRequest,
    SessionCreateRequest,
    SessionRenewRequest,
    SessionResponse,
    PlanStep,
    PlanCreateRequest,
    ApprovalSubmitRequest,
    ApprovalResponse,
)
LITERALS = {
    "RiskTier": RiskTier,
    "Mode": Mode,
    "SourceKind": SourceKind,
    "GoalVerb": GoalVerb,
    "SessionStatus": SessionStatus,
    "ApprovalDecision": ApprovalDecision,
}


def build_openapi_components() -> dict:
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "ARIN Canonical Contract Components",
            "version": "1.0.0",
            "description": "Schema-only components generated from canonical ARIN Pydantic contracts; no runtime routes or authority are implied.",
        },
        "paths": {},
        "components": {
            "schemas": {model.__name__: model.model_json_schema() for model in MODELS}
        },
    }


def _ts_union(annotation: object) -> str:
    return " | ".join(json.dumps(value) for value in get_args(annotation))


def build_typescript() -> str:
    lines = [
        "// Generated by scripts/generate_arin_contract_artifacts.py; DO NOT EDIT.",
        "// Schema-only client types. They grant no authentication, tool, or actuator authority.",
        "",
        "export type ContractVersion = \"1.0.0\";",
    ]
    for name, annotation in LITERALS.items():
        lines.append(f"export type {name} = {_ts_union(annotation)};")
    lines.extend([
        "",
        "export interface Goal { verb: GoalVerb; object: string; parameters?: Record<string, unknown>; }",
        "export interface IntentCreateRequest { source_kind: SourceKind; source_text: string; goal: Goal; requested_mode: Mode; requested_risk_tier: RiskTier; }",
        "export interface SessionCreateRequest { version?: ContractVersion; api_key: string; }",
        "export interface SessionRenewRequest { version?: ContractVersion; session_id: string; new_expires_at: string; }",
        "export interface SessionResponse { version?: ContractVersion; session_id: string; access_token: string; token_type?: \"Bearer\"; tenant_id: string; principal_id: string; scopes: string[]; expires_at: string; status?: SessionStatus; }",
        "export interface PlanStep { version?: ContractVersion; tool_id: string; arguments?: Record<string, unknown>; risk_tier?: RiskTier; }",
        "export interface PlanCreateRequest { version?: ContractVersion; session_id: string; task: string; steps: PlanStep[]; idempotency_key: string; }",
        "export interface ApprovalSubmitRequest { version?: ContractVersion; execution_id: string; approval_id: string; decision: ApprovalDecision; reason: string; }",
        "export interface ApprovalResponse { version?: ContractVersion; approval_id: string; execution_id: string; decision: ApprovalDecision; reason: string; approver_id: string; status?: \"resolved\"; }",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "arin-v1.openapi.json").write_text(
        json.dumps(build_openapi_components(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (OUT / "arin-v1.types.ts").write_text(build_typescript(), encoding="utf-8")


if __name__ == "__main__":
    main()
