#!/usr/bin/env python3
"""Run a destructive-operation-free PostgreSQL rollback rehearsal.

The rehearsal creates a uniquely named temporary database, restores a fresh
authenticated backup into it, verifies the restored schema and integrity, and
removes only that temporary database. It never replaces the source database.
This is local/rehearsal evidence; it is not staging or production rollback
evidence.
"""

from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
import re
import secrets
import sys
import tempfile
from pathlib import Path
from typing import Optional
from urllib.parse import parse_qs, quote, urlsplit, urlunsplit

# Allow the checked-in CLI to run directly from a source checkout without an
# editable install.
if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.backup_control_plane import (
    _read_backup_key,
    _restore_postgresql,
    _validate_postgresql_archive,
)
from src.control_plane.backup import encrypt_file, open_sealed
from src.control_plane.storage.postgres_storage import PostgresControlPlaneStore


_EPHEMERAL_DATABASE_RE = re.compile(r"^zasi_rollback_drill_[0-9a-f]{16}$")


class RollbackDrillError(RuntimeError):
    """Raised when a rollback rehearsal cannot be safely completed."""


@dataclass(frozen=True)
class RollbackDrillResult:
    """Sanitized evidence emitted after a successful local rehearsal."""

    schema_version: int
    source_observation_unchanged: bool
    restored_integrity: bool
    cleanup_passed: bool

    def as_dict(self) -> dict[str, object]:
        passed = (
            self.source_observation_unchanged
            and self.restored_integrity
            and self.cleanup_passed
        )
        return {
            "status": "passed" if passed else "failed",
            "mode": "local-rehearsal",
            "backend": "postgresql",
            "schema_version": self.schema_version,
            "source_observation_unchanged": self.source_observation_unchanged,
            "restored_integrity": self.restored_integrity,
            "cleanup": "passed" if self.cleanup_passed else "failed",
        }


def require_local_rehearsal(profile: str, *, acknowledged: bool) -> str:
    """Require an explicit acknowledgement and reject staging/production."""
    normalized = (profile or "").strip().lower()
    if normalized in {"staging", "production"}:
        raise RollbackDrillError(
            "staging and production rollback require an independently governed run"
        )
    if normalized not in {"local", "test"}:
        raise RollbackDrillError("rollback rehearsal requires a local or test profile")
    if not acknowledged:
        raise RollbackDrillError(
            "pass --allow-local-rehearsal to acknowledge the temporary database"
        )
    return "local-rehearsal"


def create_ephemeral_database_name() -> str:
    """Return a random database name restricted to the drill namespace."""
    return f"zasi_rollback_drill_{secrets.token_hex(8)}"


def quote_ephemeral_database_identifier(name: str) -> str:
    """Quote only names generated by this command, never arbitrary input."""
    if not _EPHEMERAL_DATABASE_RE.fullmatch(name):
        raise RollbackDrillError("temporary database name is outside the drill namespace")
    return f'"{name}"'


def _require_postgresql_url(value: str, field: str) -> None:
    if not value or not value.startswith(("postgresql://", "postgres://")):
        raise RollbackDrillError(f"{field} must be a PostgreSQL URL")
    if not urlsplit(value).path.strip("/"):
        raise RollbackDrillError(f"{field} must select a database")


def _require_local_postgresql_url(value: str, field: str) -> None:
    """Reject remote targets so a local rehearsal cannot reach production."""
    _require_postgresql_url(value, field)
    parsed = urlsplit(value)
    query = parse_qs(parsed.query, keep_blank_values=True)
    hosts = []
    if parsed.hostname:
        hosts.append(parsed.hostname)
    for raw_host in query.get("host", []):
        hosts.extend(item.strip() for item in raw_host.split(","))
    for host in hosts:
        normalized = host.lower().rstrip(".")
        if normalized in {"localhost", "127.0.0.1", "::1"}:
            continue
        if host.startswith("/"):
            continue
        raise RollbackDrillError(
            f"{field} must use localhost, loopback, or a Unix socket for local rehearsal"
        )


def _url_for_database(database_url: str, database_name: str) -> str:
    parsed = urlsplit(database_url)
    path = f"/{quote(database_name, safe='')}"
    if not parsed.netloc:
        # ``urlunsplit`` collapses the empty authority in a PostgreSQL socket
        # URL to ``postgresql:/database``. Preserve the libpq ``:///`` form.
        query = f"?{parsed.query}" if parsed.query else ""
        return f"{parsed.scheme}://{path}{query}"
    return urlunsplit(
        (
            parsed.scheme,
            parsed.netloc,
            path,
            parsed.query,
            "",
        )
    )


def _connect_admin(admin_url: str):
    try:
        import psycopg

        return psycopg.connect(
            admin_url,
            autocommit=True,
            connect_timeout=5,
            application_name="zasi-rollback-drill",
        )
    except ImportError as exc:
        raise RollbackDrillError("PostgreSQL rollback rehearsal requires psycopg") from exc
    except Exception as exc:
        raise RollbackDrillError("rollback rehearsal administrator connection failed") from exc


def _create_database(connection, name: str) -> None:
    identifier = quote_ephemeral_database_identifier(name)
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1 FROM pg_database WHERE datname = %s", (name,))
            if cursor.fetchone() is not None:
                raise RollbackDrillError("generated rollback database name already exists")
            cursor.execute(f"CREATE DATABASE {identifier}")
    except RollbackDrillError:
        raise
    except Exception as exc:
        raise RollbackDrillError("temporary rollback database creation failed") from exc


def _drop_database(connection, name: str) -> None:
    identifier = quote_ephemeral_database_identifier(name)
    try:
        with connection.cursor() as cursor:
            cursor.execute(f"DROP DATABASE IF EXISTS {identifier}")
    except Exception as exc:
        raise RollbackDrillError("temporary rollback database cleanup failed") from exc


def run_postgresql_rollback_drill(
    source_url: str,
    admin_url: str,
    *,
    expected_schema_version: Optional[int] = None,
) -> RollbackDrillResult:
    """Rehearse restore into a disposable PostgreSQL database."""
    _require_local_postgresql_url(source_url, "source URL")
    _require_local_postgresql_url(admin_url, "administrator URL")
    key = _read_backup_key()
    source = PostgresControlPlaneStore(source_url)
    admin = None
    target_store = None
    target_name = create_ephemeral_database_name()
    target_created = False

    try:
        try:
            source.initialize()
            source_schema = source.schema_version()
            source_integrity = source.integrity_check()
        except Exception as exc:
            raise RollbackDrillError("source PostgreSQL observation failed") from exc
        if not source_integrity:
            raise RollbackDrillError("source PostgreSQL integrity observation failed")
        if (
            expected_schema_version is not None
            and source_schema != expected_schema_version
        ):
            raise RollbackDrillError("source schema version does not match expectation")

        with tempfile.TemporaryDirectory(prefix="zasi-rollback-drill-") as directory:
            root = Path(directory)
            raw_backup = root / "control-plane.dump"
            sealed_backup = root / "control-plane.zasi"
            source.backup_to(str(raw_backup))
            encrypt_file(
                raw_backup,
                sealed_backup,
                backend="postgresql",
                schema_version=source_schema,
                key=key,
            )
            metadata, payload = open_sealed(sealed_backup.read_bytes(), key)
            if metadata.schema_version != source_schema:
                raise RollbackDrillError("authenticated backup schema does not match source")
            raw_backup.write_bytes(payload)
            raw_backup.chmod(0o600)
            _validate_postgresql_archive(raw_backup)

            admin = _connect_admin(admin_url)
            _create_database(admin, target_name)
            target_created = True
            target_url = _url_for_database(admin_url, target_name)
            _restore_postgresql(
                raw_backup,
                target_url,
                replace=False,
                no_owner=True,
            )

            target_store = PostgresControlPlaneStore(target_url)
            target_store.initialize()
            restored_schema = target_store.schema_version()
            restored_integrity = target_store.integrity_check()
            if restored_schema != source_schema:
                raise RollbackDrillError("restored schema version does not match source")
            if not restored_integrity:
                raise RollbackDrillError("restored PostgreSQL integrity check failed")

        source_after_schema = source.schema_version()
        source_after_integrity = source.integrity_check()
        source_unchanged = (
            source_after_schema == source_schema
            and source_after_integrity == source_integrity
        )
        if not source_unchanged:
            raise RollbackDrillError("source PostgreSQL observation changed during rehearsal")
        return RollbackDrillResult(
            schema_version=source_schema,
            source_observation_unchanged=True,
            restored_integrity=True,
            cleanup_passed=True,
        )
    except RollbackDrillError:
        raise
    except Exception as exc:
        raise RollbackDrillError("PostgreSQL rollback rehearsal failed") from exc
    finally:
        if target_store is not None:
            try:
                target_store.close()
            except Exception:
                pass
        if admin is not None and target_created:
            _drop_database(admin, target_name)
        if admin is not None:
            try:
                admin.close()
            except Exception:
                pass
        try:
            source.close()
        except Exception:
            pass


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-url",
        default=os.environ.get("ZASI_ROLLBACK_SOURCE_URL")
        or os.environ.get("ZASI_DATABASE_URL", ""),
        help="source PostgreSQL URL; defaults to ZASI_ROLLBACK_SOURCE_URL",
    )
    parser.add_argument(
        "--admin-url",
        default=os.environ.get("ZASI_ROLLBACK_ADMIN_URL", ""),
        help="administrator PostgreSQL URL used only for the temporary database",
    )
    parser.add_argument(
        "--profile",
        default=os.environ.get("ZASI_PROFILE", "local"),
    )
    parser.add_argument(
        "--allow-local-rehearsal",
        action="store_true",
        help="explicitly acknowledge creation/removal of one temporary database",
    )
    parser.add_argument("--expected-schema-version", type=int)
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    args = _parser().parse_args(argv)
    try:
        require_local_rehearsal(
            args.profile,
            acknowledged=args.allow_local_rehearsal,
        )
        result = run_postgresql_rollback_drill(
            args.source_url,
            args.admin_url,
            expected_schema_version=args.expected_schema_version,
        )
    except (RollbackDrillError, OSError, ValueError) as exc:
        print(f"rollback drill rejected: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(result.as_dict(), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
